import { Formulario } from "../../context/formularioContext/Types";

export interface FormularioFormValues extends Formulario{

  }
  
  export const initialValues: FormularioFormValues = {
nombre: "string",
  fecha: "2024-06-22",
  remision: "No remitido",
  historia_clinica: true,
  motivo_consulta: "string",
  primer_sintoma: "string",
  tiempo_de_aparicion: "Días",
  otros_sintomas: "string",
  personales_de_riesgo: "Ninguno",
  personales_patologicos: "Ninguno",
  familiares_con_cancer: "Si",
  caracteristicas_de_la_lesion: "Vegetante",
  region: "Derecha",
  tamanno_de_la_lesion: "2024-06-22",
  localizacion_en_labio: "Labio superior",
  lengua_movil: "Cara central",
  suelo_de_Boca: "Parte anterior",
  encia: "Superior",
  otras_partes_del_a_boca: "Carrillo",
  glandulas_salibales: "Parótida",
  ardenopatia_cervical_derecha: "No",
  ardenopatia_cervical_izquierda: "No",
  extension_clinica_a: "No",
  performance_status: 0,
  primer_apellido: "string",
  segundo_apellido: "string",
  nombre_del_paciente: "string",
  sexo: "Femenino",
  edad: 0,
  color_de_piel: "Blanca",
  carne_de_identidad: "string",
  historia_clinica_numero: "string",
  fecha_de_inscripcion: 0,
  creatinina: "-7717608",
  hemoglobina: "-35713934",
  imagen_rx_torax: "Ninguno",
  imagen_us_abdomen: "Ninguno",
  imagen_tac_cavidad_oral: "Ninguno",
  otros_tac_faringe: "Ninguno",
  otros_tac_cuello: "Ninguno",
  otros_tac_torax: "Ninguno",
  otros_rmn: "Ninguno",
  biopsia_numero: 0,
  fecha_de_diagnostico: "2024-06-22",
  diagnostico_topografico: "string",
  };